-- 코드를 입력하세요
SELECT
    CH.CAR_ID,
    CH.CAR_TYPE,
    TRUNCATE((CH.DAILY_FEE * ((100-P.DISCOUNT_RATE)/100)) * 30,0) AS FEE
FROM (SELECT
        CAR_TYPE,
        DISCOUNT_RATE
      FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
      WHERE DURATION_TYPE = '30일 이상') AS P
JOIN (SELECT
        C.CAR_ID,
        C.CAR_TYPE,
        C.DAILY_FEE
      FROM CAR_RENTAL_COMPANY_CAR AS C
      JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
      ON C.CAR_ID = H.CAR_ID
      WHERE C.CAR_TYPE IN ('세단', 'SUV')
      GROUP BY C.CAR_ID
      HAVING MAX(H.END_DATE) < '2022-11-01') AS CH
ON P.CAR_TYPE = CH.CAR_TYPE
WHERE TRUNCATE((CH.DAILY_FEE * ((100-P.DISCOUNT_RATE)/100)) * 30,0) >= 500000 
AND TRUNCATE((CH.DAILY_FEE * ((100-P.DISCOUNT_RATE)/100)) * 30,0) < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC

