-- 코드를 입력하세요
SELECT
    CART_ID
FROM(
SELECT CART_ID 
FROM CART_PRODUCTS
WHERE NAME = 'Milk' OR NAME = 'Yogurt'
GROUP BY CART_ID, NAME
) AS K
GROUP BY CART_ID
HAVING COUNT(CART_ID) = 2
ORDER BY CART_ID