-- 코드를 입력하세요
SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT(U.USER_ID)) AS PUCHASED_USERS,
    ROUND(COUNT(DISTINCT(U.USER_ID)) / (SELECT COUNT(USER_ID) AS USER_ID2021
                        FROM USER_INFO
                        WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'), 1) AS PUCHASED_RATIO
FROM USER_INFO AS U
JOIN ONLINE_SALE AS O
ON U.USER_ID = O.USER_ID AND U.JOINED BETWEEN '2021-01-01' AND '2021-12-31'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH