-- 코드를 입력하세요
SELECT
    MONTH(START_DATE) AS MONTH,
    CAR_ID,
    COUNT(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31' # 두번 조건을 줘야 하는 이유는 무엇인가?
AND CAR_ID IN (SELECT CAR_ID
                 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                 WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
                 GROUP BY CAR_ID
                 HAVING COUNT(HISTORY_ID) >= 5)
GROUP BY MONTH, CAR_ID
HAVING COUNT(HISTORY_ID) > 0
ORDER BY MONTH ASC, CAR_ID DESC;


# 두 번 걸어줘야 하는 이유
# 8~10월 사이에 5회 이상인 차 ID를 가져왔지만 외부쿼리에서 집계할때 다른 월이 존재할수도 있기 때문에 두 번 걸어줘야 한다.