-- 코드를 입력하세요
WITH RECURSIVE TIME AS(
    SELECT 0 as HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM TIME
    WHERE HOUR < 23)

SELECT
    T.HOUR,
    IFNULL(COUNT, 0) AS COUNT
FROM TIME AS T
LEFT JOIN (SELECT
            HOUR(DATETIME) AS HOUR,
            COUNT(ANIMAL_ID) AS COUNT
           FROM ANIMAL_OUTS
           GROUP BY HOUR) AS A
ON T.HOUR = A.HOUR