-- 코드를 입력하세요
-- 중복 제거 : DISTINCT(컬러명)
SELECT COUNT(DISTINCT(NAME)) AS COUNT
FROM ANIMAL_INS
WHERE NAME IS NOT NULL

# 중복된 이름 확인하기
# SELECT NAME, COUNT(NAME)
# FROM ANIMAL_INS
# GROUP BY NAME
# HAVING COUNT(NAME) > 1