-- 코드를 입력하세요
# 3분 17초
SELECT a.CAR_ID, ROUND(AVG(a.DATE_DIFF),1) AS AVERAGE_DURATION
FROM 
(
    SELECT 
        CAR_ID,
        (DATEDIFF(END_DATE, START_DATE) + 1) DATE_DIFF
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) a
GROUP BY a.CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, a.CAR_ID DESC;