-- 코드를 입력하세요
# 13 39
SELECT
    MEMBER_NAME,
    REVIEW_TEXT,
    DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW AS R1
JOIN
(SELECT
    MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
HAVING COUNT(MEMBER_ID) = (SELECT COUNT(MEMBER_ID)
                           FROM REST_REVIEW
                           GROUP BY MEMBER_ID
                           ORDER BY COUNT(MEMBER_ID) DESC
                           LIMIT 1)
) AS R2
ON R1.MEMBER_ID = R2.MEMBER_ID
JOIN MEMBER_PROFILE AS M
ON R1.MEMBER_ID = M.MEMBER_ID
ORDER BY REVIEW_DATE