-- 코드를 입력하세요
SELECT
    A.AUTHOR_ID,
    AUTHOR_NAME,
    CATEGORY,
    TOTAL_SALES
FROM AUTHOR AS A
JOIN(
SELECT
    B.BOOK_ID,
    B.CATEGORY,
    AUTHOR_ID,
    SUM(PRICE * COUNT_S) AS TOTAL_SALES
FROM BOOK AS B
JOIN(
SELECT
    BOOK_ID,
    SUM(SALES) AS COUNT_S
FROM BOOK_SALES
WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY BOOK_ID
) AS BS
ON B.BOOK_ID = BS.BOOK_ID
GROUP BY CATEGORY, AUTHOR_ID
) AS T
ON A.AUTHOR_ID = T.AUTHOR_ID
ORDER BY AUTHOR_ID, CATEGORY DESC