# -- 코드를 입력하세요
SELECT
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(S.TOTAL * B.PRICE) AS TOTAL_SALES
FROM BOOK AS B
JOIN AUTHOR AS A
ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN (SELECT
        BOOK_ID,
        SUM(SALES) AS TOTAL
      FROM BOOK_SALES
      WHERE SALES_DATE LIKE '2022-01%'
      GROUP BY BOOK_ID) AS S
ON B.BOOK_ID = S.BOOK_ID
GROUP BY A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC

# SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE*S.SALES) TOTAL_SALES FROM BOOK B LEFT JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID LEFT JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID WHERE S.SALES_DATE LIKE '2022-01%' GROUP BY B.AUTHOR_ID, B.CATEGORY ORDER BY A.AUTHOR_ID ASC, A.AUTHOR_NAME DESC;