-- 코드를 입력하세요
# 4분 50초
SELECT
    U1.TITLE,
    U1.BOARD_ID,
    U2.REPLY_ID,
    U2.WRITER_ID,
    U2.CONTENTS,
    DATE_FORMAT(U2.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS U1
JOIN USED_GOODS_REPLY AS U2
ON U1.BOARD_ID = U2.BOARD_ID
WHERE U1.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY U2.CREATED_DATE, U1.TITLE