-- 코드를 입력하세요
SELECT
    CH.HISTORY_ID,
    CASE
        WHEN CH.DURATION = '그 외' THEN CH.DAILY_FEE * CH.DIFFDATE
        ELSE TRUNCATE((CH.DAILY_FEE * (100 - P.DISCOUNT_RATE) / 100) * CH.DIFFDATE, 0)
    END AS FEE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
RIGHT OUTER JOIN(SELECT
        C.CAR_ID,
        C.CAR_TYPE,
        C.DAILY_FEE,
        H.HISTORY_ID,
        DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS DIFFDATE,         
     CASE 
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7  THEN '7일 이상'
        ELSE '그 외'
     END AS DURATION
     FROM CAR_RENTAL_COMPANY_CAR AS C
     JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
     ON C.CAR_ID = H.CAR_ID
     WHERE C.CAR_TYPE = '트럭'
) AS CH
ON CH.CAR_TYPE = P.CAR_TYPE AND CH.DURATION = P.DURATION_TYPE
ORDER BY FEE DESC, CH.HISTORY_ID DESC