-- 코드를 입력하세요
-- SELECT COUNT(*) AS USERS FROM USER_INFO
-- WHERE AGE BETWEEN 20 AND 29 
-- AND JOINED LIKE '2021%';

SELECT COUNT(*) AS USERS FROM USER_INFO
WHERE YEAR(JOINED) = '2021' AND AGE BETWEEN 20 AND 29;
